### ISSUE TITLE
Python 2.6 or 3.1?

### ISSUE THREAD

**Issue by cgaebel** [napcs/programming_for_kids#2]
Which version of python should I include setup for? 2.6 is hopefully going to die soon, but it seems the most common right now. Also, all the code in your repo is done in Python 2.6, but is easily upgraded to v3 with 2to3.py.

Need this answered before I write the "Getting Started - Python" docs.

**Comment by napcs** [comment]
I say just write it for 2.6 now. If we go 3 we just change it when relevant. I'm doing 1.8.7 for Ruby. jmhobbs is doing the python work.

**Comment by cgaebel** [comment]
Okay, I'll write it for 2.6 after dinner then :)

**Comment by jmhobbs** [comment]
I responded to a message, but I'm going to move the discussion here.  They just did beta 2.7 release, so that tree isn't really going to die, but I think if we are teaching kids to program, then legacy is not what we want.  I'm good with a switch to 3, it'll force me to get with the program anyway :-)
